/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baza_danych;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Tyroke
 */
public class okno_glowne extends javax.swing.JFrame {

    /**
     * Creates new form okno_glowne
     */
    baza_danych.Arduino ard = new baza_danych.Arduino();
    ImageIcon obrazek = new ImageIcon("obrazki/wirus1.jpg");
    ImageIcon obrazek0 = new ImageIcon("obrazki/wirus1.jpg");
    ImageIcon obrazek1 = new ImageIcon("obrazki/wirus2.jpg");
    ImageIcon obrazek2 = new ImageIcon("obrazki/wirus3.jpg");
    ImageIcon obrazek3 = new ImageIcon("obrazki/wirus4.jpg");
    ImageIcon obrazek4 = new ImageIcon("obrazki/wirus5.jpg");
    ImageIcon obrazek5 = new ImageIcon("obrazki/wirus6.jpg");
    ImageIcon obrazek6 = new ImageIcon("obrazki/wirus7.jpg");
    ImageIcon obrazek7 = new ImageIcon("obrazki/wirus8.jpg");
    ImageIcon obrazek8 = new ImageIcon("obrazki/wirus9.jpg");
    ImageIcon obrazek9 = new ImageIcon("obrazki/wirus10.jpg");
    ImageIcon obrazek10 = new ImageIcon("obrazki/zgon1.jpg");
    ImageIcon obrazek11 = new ImageIcon("obrazki/zgon2.jpg");
    ImageIcon obrazek12 = new ImageIcon("obrazki/zgon3.jpg");
    ImageIcon obrazek13 = new ImageIcon("obrazki/zgon4.jpg");
    ImageIcon obrazek14 = new ImageIcon("obrazki/zgon5.jpg");
    ImageIcon obrazek15 = new ImageIcon("obrazki/zgon6.jpg");
    ImageIcon obrazek16 = new ImageIcon("obrazki/zgon7.jpg");
    ImageIcon obrazek17 = new ImageIcon("obrazki/zgon8.jpg");
    ImageIcon obrazek18 = new ImageIcon("obrazki/zgon9.jpg");
    ImageIcon obrazek19 = new ImageIcon("obrazki/zgon10.jpg");
    ImageIcon obrazek20 = new ImageIcon("obrazki/zgon11.jpg");
    ImageIcon obrazek21 = new ImageIcon("obrazki/zgon12.jpg");
    ImageIcon obrazek22 = new ImageIcon("obrazki/zgon13.jpg");
    ImageIcon obrazek23 = new ImageIcon("obrazki/zgon14.jpg");
    ImageIcon obrazek24 = new ImageIcon("obrazki/zgon15.jpg");
    ImageIcon obrazek25 = new ImageIcon("obrazki/zgon16.jpg");
    ImageIcon obrazek26 = new ImageIcon("obrazki/zgon17.jpg");
    ImageIcon obrazek27 = new ImageIcon("obrazki/zgon18.jpg");
    ImageIcon obrazek28 = new ImageIcon("obrazki/zgon19.jpg");
    ImageIcon obrazek29 = new ImageIcon("obrazki/zgon20.jpg");
    
    
    String haslo_haslo = "";
    String prawdziwe_haslo = "18221";
    int[] zamknij_haslo2 = new int[5];
    int licznik_zamknij = 0;
    char znak;
    int licznik_zgony = 0;
    int licznik_wirusy = 0;
    int moment = 0;

    public okno_glowne() {
        zamknij_haslo2[0] = 4;
        zamknij_haslo2[1] = 3;
        zamknij_haslo2[2] = 2;
        zamknij_haslo2[3] = 1;
        initComponents();
        zgony_opis.setText("Śmierć była krótka.");
        wirusy_zdjecie.setIcon(obrazek0);
        zgony_zdjecie.setIcon(obrazek5);
        wirusy_opis.setText("Dziwny wirus1 wirus.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logowanie = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        login_logowanie = new javax.swing.JTextField();
        OK_logowanie = new javax.swing.JButton();
        komunikat = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        komunikat_tekst = new javax.swing.JTextArea();
        komunikat_zamknij = new javax.swing.JButton();
        zgony_okno = new javax.swing.JFrame();
        zgony_poprzedni = new javax.swing.JButton();
        zgony_nastepny = new javax.swing.JButton();
        zgony_zdjecie = new javax.swing.JLabel();
        zgony_wyjdz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        zgony_opis = new javax.swing.JTextArea();
        wirusy_okno = new javax.swing.JFrame();
        wirusy_zdjecie = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wirusy_opis = new javax.swing.JTextArea();
        wirusy_poprzedni = new javax.swing.JButton();
        wirusy_nastepny = new javax.swing.JButton();
        wirusy_zamknij = new javax.swing.JButton();
        haslo = new javax.swing.JFrame();
        haslo_tekst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        haslo_7 = new javax.swing.JButton();
        haslo_8 = new javax.swing.JButton();
        haslo_9 = new javax.swing.JButton();
        haslo_4 = new javax.swing.JButton();
        haslo_5 = new javax.swing.JButton();
        haslo_6 = new javax.swing.JButton();
        haslo_1 = new javax.swing.JButton();
        haslo_2 = new javax.swing.JButton();
        haslo_3 = new javax.swing.JButton();
        haslo_ok = new javax.swing.JButton();
        haslo_kasuj = new javax.swing.JButton();
        strzalki_okno = new javax.swing.JFrame();
        zamknij_haslo = new javax.swing.JFrame();
        zamknij_1 = new javax.swing.JButton();
        zamknij_2 = new javax.swing.JButton();
        zamknij_3 = new javax.swing.JButton();
        zamknij_4 = new javax.swing.JButton();
        zamknij_5 = new javax.swing.JButton();
        zamknij_zamknij = new javax.swing.JButton();
        uprawnienia = new javax.swing.JButton();
        wirusy = new javax.swing.JButton();
        zgony = new javax.swing.JButton();
        uzytkownik = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        strzalki = new javax.swing.JButton();
        tlo = new javax.swing.JLabel();
        zaloguj = new javax.swing.JButton();
        klawiatura = new javax.swing.JButton();
        zamknij = new javax.swing.JButton();

        logowanie.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        logowanie.setTitle("Logowanie");
        logowanie.setAlwaysOnTop(true);
        logowanie.setFocusTraversalPolicyProvider(true);
        logowanie.setLocation(new java.awt.Point(300, 50));
        logowanie.setName("Logowanie"); // NOI18N
        logowanie.setUndecorated(true);
        logowanie.setResizable(false);
        logowanie.setSize(new java.awt.Dimension(400, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Podaj login:");
        jLabel1.setEnabled(false);

        login_logowanie.setEditable(false);
        login_logowanie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login_logowanie.setText("Ila Cramerotti");

        OK_logowanie.setText("OK");
        OK_logowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_logowanieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logowanieLayout = new javax.swing.GroupLayout(logowanie.getContentPane());
        logowanie.getContentPane().setLayout(logowanieLayout);
        logowanieLayout.setHorizontalGroup(
            logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logowanieLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_logowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(OK_logowanie)
                .addGap(36, 36, 36))
        );
        logowanieLayout.setVerticalGroup(
            logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logowanieLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_logowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OK_logowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        komunikat.setAlwaysOnTop(true);
        komunikat.setLocation(new java.awt.Point(300, 50));
        komunikat.setUndecorated(true);
        komunikat.setSize(new java.awt.Dimension(400, 229));

        komunikat_tekst.setEditable(false);
        komunikat_tekst.setColumns(20);
        komunikat_tekst.setRows(5);
        jScrollPane2.setViewportView(komunikat_tekst);

        komunikat_zamknij.setText("Zamknij");
        komunikat_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komunikat_zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout komunikatLayout = new javax.swing.GroupLayout(komunikat.getContentPane());
        komunikat.getContentPane().setLayout(komunikatLayout);
        komunikatLayout.setHorizontalGroup(
            komunikatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(komunikatLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, komunikatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(komunikat_zamknij)
                .addGap(41, 41, 41))
        );
        komunikatLayout.setVerticalGroup(
            komunikatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(komunikatLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(komunikat_zamknij)
                .addGap(25, 25, 25))
        );

        zgony_okno.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        zgony_okno.setTitle("Lista zgonów");
        zgony_okno.setAlwaysOnTop(true);
        zgony_okno.setLocation(new java.awt.Point(300, 140));
        zgony_okno.setUndecorated(true);
        zgony_okno.setResizable(false);
        zgony_okno.setSize(new java.awt.Dimension(770, 475));

        zgony_poprzedni.setText("Poprzedni");
        zgony_poprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zgony_poprzedniActionPerformed(evt);
            }
        });

        zgony_nastepny.setText("Następny");
        zgony_nastepny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zgony_nastepnyActionPerformed(evt);
            }
        });

        zgony_wyjdz.setText("Zamknij");
        zgony_wyjdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zgony_wyjdzActionPerformed(evt);
            }
        });

        zgony_opis.setEditable(false);
        zgony_opis.setColumns(20);
        zgony_opis.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        zgony_opis.setRows(5);
        zgony_opis.setText("\n");
        jScrollPane1.setViewportView(zgony_opis);

        javax.swing.GroupLayout zgony_oknoLayout = new javax.swing.GroupLayout(zgony_okno.getContentPane());
        zgony_okno.getContentPane().setLayout(zgony_oknoLayout);
        zgony_oknoLayout.setHorizontalGroup(
            zgony_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zgony_oknoLayout.createSequentialGroup()
                .addComponent(zgony_zdjecie, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(zgony_oknoLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(zgony_poprzedni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zgony_nastepny)
                .addGap(113, 113, 113)
                .addComponent(zgony_wyjdz)
                .addGap(20, 20, 20))
        );
        zgony_oknoLayout.setVerticalGroup(
            zgony_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zgony_oknoLayout.createSequentialGroup()
                .addGroup(zgony_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zgony_zdjecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(zgony_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zgony_poprzedni)
                    .addComponent(zgony_nastepny)
                    .addComponent(zgony_wyjdz))
                .addGap(24, 24, 24))
        );

        wirusy_okno.setAlwaysOnTop(true);
        wirusy_okno.setLocation(new java.awt.Point(300, 140));
        wirusy_okno.setUndecorated(true);
        wirusy_okno.setResizable(false);
        wirusy_okno.setSize(new java.awt.Dimension(770, 475));

        wirusy_opis.setEditable(false);
        wirusy_opis.setColumns(20);
        wirusy_opis.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        wirusy_opis.setRows(5);
        jScrollPane3.setViewportView(wirusy_opis);

        wirusy_poprzedni.setText("Poprzedni");
        wirusy_poprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wirusy_poprzedniActionPerformed(evt);
            }
        });

        wirusy_nastepny.setText("Następny");
        wirusy_nastepny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wirusy_nastepnyActionPerformed(evt);
            }
        });

        wirusy_zamknij.setText("Zamknij");
        wirusy_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wirusy_zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wirusy_oknoLayout = new javax.swing.GroupLayout(wirusy_okno.getContentPane());
        wirusy_okno.getContentPane().setLayout(wirusy_oknoLayout);
        wirusy_oknoLayout.setHorizontalGroup(
            wirusy_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wirusy_oknoLayout.createSequentialGroup()
                .addComponent(wirusy_zdjecie, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(wirusy_oknoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wirusy_poprzedni)
                .addGap(140, 140, 140)
                .addComponent(wirusy_nastepny)
                .addGap(115, 115, 115)
                .addComponent(wirusy_zamknij)
                .addGap(22, 22, 22))
        );
        wirusy_oknoLayout.setVerticalGroup(
            wirusy_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wirusy_oknoLayout.createSequentialGroup()
                .addGroup(wirusy_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(wirusy_zdjecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(wirusy_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wirusy_poprzedni)
                    .addComponent(wirusy_nastepny)
                    .addComponent(wirusy_zamknij))
                .addGap(31, 31, 31))
        );

        haslo.setAlwaysOnTop(true);
        haslo.setLocation(new java.awt.Point(300, 50));
        haslo.setUndecorated(true);
        haslo.setResizable(false);
        haslo.setSize(new java.awt.Dimension(405, 315));

        haslo_tekst.setEditable(false);

        jLabel2.setText("Podaj hasło:");

        haslo_7.setText("7");
        haslo_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_7ActionPerformed(evt);
            }
        });

        haslo_8.setText("8");
        haslo_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_8ActionPerformed(evt);
            }
        });

        haslo_9.setText("9");
        haslo_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_9ActionPerformed(evt);
            }
        });

        haslo_4.setText("4");
        haslo_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_4ActionPerformed(evt);
            }
        });

        haslo_5.setText("5");
        haslo_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_5ActionPerformed(evt);
            }
        });

        haslo_6.setText("6");
        haslo_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_6ActionPerformed(evt);
            }
        });

        haslo_1.setText("1");
        haslo_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_1ActionPerformed(evt);
            }
        });

        haslo_2.setText("2");
        haslo_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_2ActionPerformed(evt);
            }
        });

        haslo_3.setText("3");
        haslo_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_3ActionPerformed(evt);
            }
        });

        haslo_ok.setText("OK");
        haslo_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_okActionPerformed(evt);
            }
        });

        haslo_kasuj.setText("Kasuj");
        haslo_kasuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haslo_kasujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hasloLayout = new javax.swing.GroupLayout(haslo.getContentPane());
        haslo.getContentPane().setLayout(hasloLayout);
        hasloLayout.setHorizontalGroup(
            hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasloLayout.createSequentialGroup()
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hasloLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(haslo_ok))
                    .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hasloLayout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel2))
                        .addGroup(hasloLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(haslo_4)
                                .addComponent(haslo_7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(haslo_1)))))
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasloLayout.createSequentialGroup()
                        .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hasloLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(haslo_tekst, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hasloLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(hasloLayout.createSequentialGroup()
                                        .addComponent(haslo_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(haslo_3))
                                    .addGroup(hasloLayout.createSequentialGroup()
                                        .addComponent(haslo_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(haslo_6))
                                    .addGroup(hasloLayout.createSequentialGroup()
                                        .addComponent(haslo_8)
                                        .addGap(81, 81, 81)
                                        .addComponent(haslo_9)))))
                        .addGap(70, 70, 70))
                    .addGroup(hasloLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(haslo_kasuj)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        hasloLayout.setVerticalGroup(
            hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasloLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haslo_tekst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haslo_7)
                    .addComponent(haslo_8)
                    .addComponent(haslo_9))
                .addGap(38, 38, 38)
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haslo_4)
                    .addComponent(haslo_5)
                    .addComponent(haslo_6))
                .addGap(44, 44, 44)
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haslo_1)
                    .addComponent(haslo_2)
                    .addComponent(haslo_3))
                .addGap(18, 18, 18)
                .addGroup(hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haslo_kasuj)
                    .addComponent(haslo_ok))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        strzalki_okno.setAlwaysOnTop(true);

        javax.swing.GroupLayout strzalki_oknoLayout = new javax.swing.GroupLayout(strzalki_okno.getContentPane());
        strzalki_okno.getContentPane().setLayout(strzalki_oknoLayout);
        strzalki_oknoLayout.setHorizontalGroup(
            strzalki_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        strzalki_oknoLayout.setVerticalGroup(
            strzalki_oknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        zamknij_haslo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        zamknij_haslo.setTitle("Zamknij");
        zamknij_haslo.setAlwaysOnTop(true);
        zamknij_haslo.setLocation(new java.awt.Point(300, 50));
        zamknij_haslo.setName("Zamknij"); // NOI18N
        zamknij_haslo.setUndecorated(true);
        zamknij_haslo.setResizable(false);
        zamknij_haslo.setSize(new java.awt.Dimension(400, 300));

        zamknij_1.setText("1");
        zamknij_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknij_1ActionPerformed(evt);
            }
        });

        zamknij_2.setText("2");
        zamknij_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknij_2ActionPerformed(evt);
            }
        });

        zamknij_3.setText("3");
        zamknij_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknij_3ActionPerformed(evt);
            }
        });

        zamknij_4.setText("4");
        zamknij_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknij_4ActionPerformed(evt);
            }
        });

        zamknij_5.setText("5");
        zamknij_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknij_5ActionPerformed(evt);
            }
        });

        zamknij_zamknij.setText("Zamknij");
        zamknij_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknij_zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zamknij_hasloLayout = new javax.swing.GroupLayout(zamknij_haslo.getContentPane());
        zamknij_haslo.getContentPane().setLayout(zamknij_hasloLayout);
        zamknij_hasloLayout.setHorizontalGroup(
            zamknij_hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zamknij_hasloLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(zamknij_1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(zamknij_2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(zamknij_3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(zamknij_hasloLayout.createSequentialGroup()
                .addGroup(zamknij_hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zamknij_hasloLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(zamknij_4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(zamknij_5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(zamknij_hasloLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(zamknij_zamknij)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zamknij_hasloLayout.setVerticalGroup(
            zamknij_hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zamknij_hasloLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(zamknij_hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zamknij_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamknij_2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamknij_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(zamknij_hasloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zamknij_4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamknij_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(zamknij_zamknij)
                .addGap(28, 28, 28))
        );

        zamknij_haslo.getAccessibleContext().setAccessibleName("");

        setTitle("Baza danych");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        uprawnienia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uprawnienia.setText("Uprawnienia");
        uprawnienia.setEnabled(false);
        uprawnienia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uprawnieniaActionPerformed(evt);
            }
        });

        wirusy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wirusy.setText("Lista wirusów");
        wirusy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wirusyActionPerformed(evt);
            }
        });

        zgony.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zgony.setText("Lista zgonów");
        zgony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zgonyActionPerformed(evt);
            }
        });

        uzytkownik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uzytkownik.setText("Użytkownik");
        uzytkownik.setEnabled(false);
        uzytkownik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uzytkownikActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login.setText("Login: ");
        login.setBorder(new javax.swing.border.MatteBorder(null));
        login.setEnabled(false);

        strzalki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        strzalki.setText("Strzałki");
        strzalki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strzalkiActionPerformed(evt);
            }
        });

        zaloguj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zaloguj.setText("Zaloguj");
        zaloguj.setEnabled(false);
        zaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujActionPerformed(evt);
            }
        });

        klawiatura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        klawiatura.setText("Klawiatura");
        klawiatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klawiaturaActionPerformed(evt);
            }
        });

        zamknij.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zamknij.setText("Zamknij");
        zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(367, 367, 367))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wirusy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uprawnienia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(klawiatura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(tlo, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(zgony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uzytkownik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(strzalki, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(klawiatura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uzytkownik, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strzalki, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uprawnienia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zgony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wirusy, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tlo, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uprawnieniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uprawnieniaActionPerformed
        haslo.setVisible(true);
        haslo_haslo = "";
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_uprawnieniaActionPerformed

    private void wirusyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wirusyActionPerformed
        // TODO add your handling code here:
        wirusy_okno.setVisible(true);

    }//GEN-LAST:event_wirusyActionPerformed

    private void zgonyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zgonyActionPerformed
        // TODO add your handling code here:
        zgony_okno.setVisible(true);
    }//GEN-LAST:event_zgonyActionPerformed

    private void uzytkownikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uzytkownikActionPerformed
        // TODO add your handling code here:
        komunikat.setVisible(true);
        komunikat_tekst.setText("Proszę przycisnąć przycisk zamknij i poczekać \n2 sekundy na identyfikację.");
        moment = 2;
    }//GEN-LAST:event_uzytkownikActionPerformed

    private void OK_logowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_logowanieActionPerformed
        // TODO add your handling code here:
        zgony.setEnabled(true);
        wirusy.setEnabled(true);
        uprawnienia.setEnabled(true);
        login.setText("Login: Administrator");
        logowanie.setVisible(false);
        zaloguj.setEnabled(false);
//        tlo.setIcon(obrazek);
    }//GEN-LAST:event_OK_logowanieActionPerformed

    private void zgony_wyjdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zgony_wyjdzActionPerformed
        // TODO add your handling code here:
        zgony_okno.setVisible(false);
    }//GEN-LAST:event_zgony_wyjdzActionPerformed

    private void haslo_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_7ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "7";
        }
        haslo_tekst.setText(haslo_haslo);

    }//GEN-LAST:event_haslo_7ActionPerformed

    private void haslo_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_8ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "8";
        }
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_haslo_8ActionPerformed

    private void haslo_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_9ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "9";
        }
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_haslo_9ActionPerformed

    private void haslo_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_4ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "4";
        }

        haslo_tekst.setText(haslo_haslo);

    }//GEN-LAST:event_haslo_4ActionPerformed

    private void haslo_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_5ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "5";
        }

        haslo_tekst.setText(haslo_haslo);

    }//GEN-LAST:event_haslo_5ActionPerformed

    private void haslo_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_6ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "6";
        }
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_haslo_6ActionPerformed

    private void haslo_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_1ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "1";
        }
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_haslo_1ActionPerformed

    private void haslo_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_2ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "2";
        }
        haslo_tekst.setText(haslo_haslo);

    }//GEN-LAST:event_haslo_2ActionPerformed

    private void haslo_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_3ActionPerformed
        // TODO add your handling code here:
        if (haslo_haslo.length() < 10) {
            haslo_haslo = haslo_haslo + "3";
        }
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_haslo_3ActionPerformed

    private void haslo_kasujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_kasujActionPerformed
        // TODO add your handling code here:
        haslo_haslo = "";
        haslo_tekst.setText(haslo_haslo);
    }//GEN-LAST:event_haslo_kasujActionPerformed

    private void haslo_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haslo_okActionPerformed
        // TODO add your handling code here:
        haslo.setVisible(false);
        if (haslo_haslo.equals(prawdziwe_haslo)) {
            komunikat.setVisible(true);
            komunikat_tekst.setText("Poprawne hasło. Proszę nacisnąć zamknij i poczekać \n2 sekundy na rejestrację.");

            moment = 1;

        } else {
            komunikat.setVisible(true);
            komunikat_tekst.setText("Błędne hasło.");
            moment = 0;
        }
    }//GEN-LAST:event_haslo_okActionPerformed

    private void komunikat_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komunikat_zamknijActionPerformed
        // TODO add your handling code here:=2;
        if (moment == 5) {
            moment = 10;
        }
        if (moment == 2) {
            moment = 4;
        }
        if (moment == 3) {
            moment = 2;
        }
        if (moment != 5 && moment != 3) {
            komunikat.setVisible(false);
        }
        if (moment == 1 && haslo_haslo.equals(prawdziwe_haslo)) {
            komunikat.setVisible(false);
            znak = 'x';
            try {
                // TODO add your handling code here:
                ard.send("odczyt1");
            } catch (InterruptedException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            }
            while (true) {
                try {
                    znak = ard.read();
                } catch (InterruptedException ex) {
                    Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (znak == '2') {
                    uzytkownik.setEnabled(true);
                    uprawnienia.setEnabled(false);
                    komunikat.setVisible(true);
                    komunikat_tekst.setText("Zapisano użykownika.");
                    moment = 3;
                    break;
                }
            }
        }
        if (moment == 4) {
            komunikat.setVisible(false);
            znak = 'x';
            try {
                // TODO add your handling code here:
                ard.send("odczyt2");
            } catch (InterruptedException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            }
            while (true) {
                try {
                    znak = ard.read();
                } catch (InterruptedException ex) {
                    Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (znak == '3') {
                    uzytkownik.setEnabled(false);
                    strzalki.setEnabled(true);
                    komunikat.setVisible(true);
                    komunikat_tekst.setText("Zidentyfikowano użykownika.");
                    moment++;
                    break;
                }
            }
        }

    }//GEN-LAST:event_komunikat_zamknijActionPerformed

    private void zalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujActionPerformed
        // TODO add your handling code here:
        logowanie.setVisible(true);
    }//GEN-LAST:event_zalogujActionPerformed

    private void klawiaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klawiaturaActionPerformed
        znak = 'x';
        try {
            // TODO add your handling code h    ere:
            ard.send("klawiatura");
        } catch (InterruptedException ex) {
            Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (true) {
            try {
                znak = ard.read();
            } catch (InterruptedException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (znak == '1') {
                klawiatura.setEnabled(false);
                zaloguj.setEnabled(true);
                break;
            }
            if (znak == 'b') {
                klawiatura.setEnabled(true);
                break;
            }
        }
    }//GEN-LAST:event_klawiaturaActionPerformed

    private void strzalkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strzalkiActionPerformed
        try {
            // TODO add your handling code here:
            ard.send("koniec");
        } catch (InterruptedException ex) {
            Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (true) {
            try {
                znak = ard.read();
            } catch (InterruptedException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (znak == '/') {
                strzalki.setEnabled(false);
                break;
            }
            if (znak == 'c') {
                strzalki.setEnabled(true);
                break;
            }

        }
    }//GEN-LAST:event_strzalkiActionPerformed

    private void zgony_nastepnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zgony_nastepnyActionPerformed
        // TODO add your handling code here:
        if (licznik_zgony > 18) {
            licznik_zgony = 0;
        } else {
            licznik_zgony++;
        }
        if (licznik_zgony == 0) {
            zgony_zdjecie.setIcon(obrazek10);
            zgony_opis.setText("Śmierć była krótka.");
        }
        if (licznik_zgony == 1) {
            zgony_zdjecie.setIcon(obrazek11);
            zgony_opis.setText("Śmierć była bolesna.");
        }
        if (licznik_zgony == 2) {
            zgony_zdjecie.setIcon(obrazek12);
            zgony_opis.setText("Śmierć była straszna.");
        }
        if (licznik_zgony == 3) {
            zgony_zdjecie.setIcon(obrazek13);
            zgony_opis.setText("Śmierć była szybka.");
        }
        if (licznik_zgony == 4) {
            zgony_zdjecie.setIcon(obrazek14);
            zgony_opis.setText("Śmierć była dziwna1.");
        }
        if (licznik_zgony == 5) {
            zgony_zdjecie.setIcon(obrazek15);
            zgony_opis.setText("Śmierć była dziwna2.");
        }
        if (licznik_zgony == 6) {
            zgony_zdjecie.setIcon(obrazek16);
            zgony_opis.setText("Śmierć była dziwna3.");
        }
        if (licznik_zgony == 7) {
            zgony_zdjecie.setIcon(obrazek17);
            zgony_opis.setText("Śmierć była dziwna4.");
        }
        if (licznik_zgony == 8) {
            zgony_zdjecie.setIcon(obrazek18);
            zgony_opis.setText("Śmierć była dziwna5.");
        }
        if (licznik_zgony == 9) {
            zgony_zdjecie.setIcon(obrazek19);
            zgony_opis.setText("Śmierć była dziwna6.");
        }
        if (licznik_zgony == 10) {
            zgony_zdjecie.setIcon(obrazek20);
            zgony_opis.setText("Śmierć była dziwna7.");
        }
        if (licznik_zgony == 11) {
            zgony_zdjecie.setIcon(obrazek21);
            zgony_opis.setText("Śmierć była dziwna8.");
        }
        if (licznik_zgony == 12) {
            zgony_zdjecie.setIcon(obrazek22);
            zgony_opis.setText("Śmierć była dziwna9.");
        }
        if (licznik_zgony == 13) {
            zgony_zdjecie.setIcon(obrazek23);
            zgony_opis.setText("Śmierć była dziwna10.");
        }
        if (licznik_zgony == 14) {
            zgony_zdjecie.setIcon(obrazek24);
            zgony_opis.setText("Śmierć była dziwna11.");
        }
        if (licznik_zgony == 15) {
            zgony_zdjecie.setIcon(obrazek25);
            zgony_opis.setText("Śmierć była dziwna12.");
        }
        if (licznik_zgony == 16) {
            zgony_zdjecie.setIcon(obrazek26);
            zgony_opis.setText("Śmierć była dziwna13.");
        }
        if (licznik_zgony == 17) {
            zgony_zdjecie.setIcon(obrazek27);
            zgony_opis.setText("Śmierć była dziwna14.");
        }
        if (licznik_zgony == 18) {
            zgony_zdjecie.setIcon(obrazek28);
            zgony_opis.setText("Śmierć była dziwna15.");
        }
        if (licznik_zgony == 19) {
            zgony_zdjecie.setIcon(obrazek29);
            zgony_opis.setText("Śmierć była dziwna16.");
        }

    }//GEN-LAST:event_zgony_nastepnyActionPerformed

    private void zgony_poprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zgony_poprzedniActionPerformed
        // TODO add your handling code here:
        if (licznik_zgony < 1) {
            licznik_zgony = 19;
        } else {
            licznik_zgony--;
        }
        if (licznik_zgony == 0) {
            zgony_zdjecie.setIcon(obrazek10);
            zgony_opis.setText("Śmierć była krótka.");
        }
        if (licznik_zgony == 1) {
            zgony_zdjecie.setIcon(obrazek11);
            zgony_opis.setText("Śmierć była bolesna.");
        }
        if (licznik_zgony == 2) {
            zgony_zdjecie.setIcon(obrazek12);
            zgony_opis.setText("Śmierć była straszna.");
        }
        if (licznik_zgony == 3) {
            zgony_zdjecie.setIcon(obrazek13);
            zgony_opis.setText("Śmierć była szybka.");
        }
        if (licznik_zgony == 4) {
            zgony_zdjecie.setIcon(obrazek14);
            zgony_opis.setText("Śmierć była dziwna1.");
        }
        if (licznik_zgony == 5) {
            zgony_zdjecie.setIcon(obrazek15);
            zgony_opis.setText("Śmierć była dziwna2.");
        }
        if (licznik_zgony == 6) {
            zgony_zdjecie.setIcon(obrazek16);
            zgony_opis.setText("Śmierć była dziwna3.");
        }
        if (licznik_zgony == 7) {
            zgony_zdjecie.setIcon(obrazek17);
            zgony_opis.setText("Śmierć była dziwna4.");
        }
        if (licznik_zgony == 8) {
            zgony_zdjecie.setIcon(obrazek18);
            zgony_opis.setText("Śmierć była dziwna5.");
        }
        if (licznik_zgony == 9) {
            zgony_zdjecie.setIcon(obrazek19);
            zgony_opis.setText("Śmierć była dziwna6.");
        }
        if (licznik_zgony == 10) {
            zgony_zdjecie.setIcon(obrazek20);
            zgony_opis.setText("Śmierć była dziwna7.");
        }
        if (licznik_zgony == 11) {
            zgony_zdjecie.setIcon(obrazek21);
            zgony_opis.setText("Śmierć była dziwna8.");
        }
        if (licznik_zgony == 12) {
            zgony_zdjecie.setIcon(obrazek22);
            zgony_opis.setText("Śmierć była dziwna9.");
        }
        if (licznik_zgony == 13) {
            zgony_zdjecie.setIcon(obrazek23);
            zgony_opis.setText("Śmierć była dziwna10.");
        }
        if (licznik_zgony == 14) {
            zgony_zdjecie.setIcon(obrazek24);
            zgony_opis.setText("Śmierć była dziwna11.");
        }
        if (licznik_zgony == 15) {
            zgony_zdjecie.setIcon(obrazek25);
            zgony_opis.setText("Śmierć była dziwna12.");
        }
        if (licznik_zgony == 16) {
            zgony_zdjecie.setIcon(obrazek26);
            zgony_opis.setText("Śmierć była dziwna13.");
        }
        if (licznik_zgony == 17) {
            zgony_zdjecie.setIcon(obrazek27);
            zgony_opis.setText("Śmierć była dziwna14.");
        }
        if (licznik_zgony == 18) {
            zgony_zdjecie.setIcon(obrazek28);
            zgony_opis.setText("Śmierć była dziwna15.");
        }
        if (licznik_zgony == 19) {
            zgony_zdjecie.setIcon(obrazek29);
            zgony_opis.setText("Śmierć była dziwna16.");
        }

    }//GEN-LAST:event_zgony_poprzedniActionPerformed

    private void zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijActionPerformed
        zamknij_haslo.setVisible(true);

        //System.exit(0);
    }//GEN-LAST:event_zamknijActionPerformed

    private void wirusy_poprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wirusy_poprzedniActionPerformed
        // TODO add your handling code here:
        if (licznik_wirusy < 1) {
            licznik_wirusy = 9;
        } else {
            licznik_wirusy--;
        }
        if (licznik_wirusy == 0) {
            wirusy_zdjecie.setIcon(obrazek0);
            wirusy_opis.setText("Dziwny wirus1 wirus.");
        }
        if (licznik_wirusy == 1) {
            wirusy_zdjecie.setIcon(obrazek1);
            wirusy_opis.setText("Straszny wirus2 wirus.");
        }
        if (licznik_wirusy == 2) {
            wirusy_zdjecie.setIcon(obrazek2);
            wirusy_opis.setText("Zabójczy wirus3 wirus.");
        }
        if (licznik_wirusy == 3) {
            wirusy_zdjecie.setIcon(obrazek3);
            wirusy_opis.setText("Niegroźny wirus4 wirus.");
        }
        if (licznik_wirusy == 4) {
            wirusy_zdjecie.setIcon(obrazek4);
            wirusy_opis.setText("Biały wirus1.");
        }
        if (licznik_wirusy == 5) {
            wirusy_zdjecie.setIcon(obrazek5);
            wirusy_opis.setText("Biały wirus2.");
        }
        if (licznik_wirusy == 6) {
            wirusy_zdjecie.setIcon(obrazek6);
            wirusy_opis.setText("Biały wirus3.");
        }
        if (licznik_wirusy == 7) {
            wirusy_zdjecie.setIcon(obrazek7);
            wirusy_opis.setText("Biały wirus4.");
        }
        if (licznik_wirusy == 8) {
            wirusy_zdjecie.setIcon(obrazek8);
            wirusy_opis.setText("Biały wirus5.");
        }
        if (licznik_wirusy == 9) {
            wirusy_zdjecie.setIcon(obrazek9);
            wirusy_opis.setText("Biały wirus6.");
        }
   


    }//GEN-LAST:event_wirusy_poprzedniActionPerformed

    private void wirusy_nastepnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wirusy_nastepnyActionPerformed
        // TODO add your handling code here:
        if (licznik_wirusy > 8) {
            licznik_wirusy = 0;
        } else {
            licznik_wirusy++;
        }
              if (licznik_wirusy == 0) {
            wirusy_zdjecie.setIcon(obrazek0);
            wirusy_opis.setText("Dziwny wirus1 wirus.");
        }
        if (licznik_wirusy == 1) {
            wirusy_zdjecie.setIcon(obrazek1);
            wirusy_opis.setText("Straszny wirus2 wirus.");
        }
        if (licznik_wirusy == 2) {
            wirusy_zdjecie.setIcon(obrazek2);
            wirusy_opis.setText("Zabójczy wirus3 wirus.");
        }
        if (licznik_wirusy == 3) {
            wirusy_zdjecie.setIcon(obrazek3);
            wirusy_opis.setText("Niegroźny wirus4 wirus.");
        }
        if (licznik_wirusy == 4) {
            wirusy_zdjecie.setIcon(obrazek4);
            wirusy_opis.setText("Biały wirus1.");
        }
        if (licznik_wirusy == 5) {
            wirusy_zdjecie.setIcon(obrazek5);
            wirusy_opis.setText("Biały wirus2.");
        }
        if (licznik_wirusy == 6) {
            wirusy_zdjecie.setIcon(obrazek6);
            wirusy_opis.setText("Biały wirus3.");
        }
        if (licznik_wirusy == 7) {
            wirusy_zdjecie.setIcon(obrazek7);
            wirusy_opis.setText("Biały wirus4.");
        }
        if (licznik_wirusy == 8) {
            wirusy_zdjecie.setIcon(obrazek8);
            wirusy_opis.setText("Biały wirus5.");
        }
        if (licznik_wirusy == 9) {
            wirusy_zdjecie.setIcon(obrazek9);
            wirusy_opis.setText("Biały wirus6.");
        }
    }//GEN-LAST:event_wirusy_nastepnyActionPerformed

    private void wirusy_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wirusy_zamknijActionPerformed
        // TODO add your handling code here:
        wirusy_okno.setVisible(false);
    }//GEN-LAST:event_wirusy_zamknijActionPerformed

    private void zamknij_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknij_1ActionPerformed
        // TODO add your handling code here:
        if (zamknij_haslo2[licznik_zamknij] == 1) {
            licznik_zamknij++;
        } else {
            licznik_zamknij = 0;
        }
    }//GEN-LAST:event_zamknij_1ActionPerformed

    private void zamknij_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknij_2ActionPerformed
        // TODO add your handling code here:
        if (zamknij_haslo2[licznik_zamknij] == 2) {
            licznik_zamknij++;
        } else {
            licznik_zamknij = 0;
        }
    }//GEN-LAST:event_zamknij_2ActionPerformed

    private void zamknij_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknij_3ActionPerformed
        // TODO add your handling code here:
        if (zamknij_haslo2[licznik_zamknij] == 3) {
            licznik_zamknij++;
        } else {
            licznik_zamknij = 0;
        }
    }//GEN-LAST:event_zamknij_3ActionPerformed

    private void zamknij_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknij_4ActionPerformed
        // TODO add your handling code here:
        if (zamknij_haslo2[licznik_zamknij] == 4) {
            licznik_zamknij++;
        } else {
            licznik_zamknij = 0;
        }
    }//GEN-LAST:event_zamknij_4ActionPerformed

    private void zamknij_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknij_5ActionPerformed
        // TODO add your handling code here:
        if (zamknij_haslo2[licznik_zamknij] == 5) {
            licznik_zamknij++;
        } else {
            licznik_zamknij = 0;
        }
    }//GEN-LAST:event_zamknij_5ActionPerformed

    private void zamknij_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknij_zamknijActionPerformed
        // TODO add your handling code here:
        if (licznik_zamknij < 4) {
            zamknij_haslo.setVisible(false);
        } else {
            try {
                // TODO add your handling code here:
                ard.send("zamknij");
            } catch (InterruptedException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(okno_glowne.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
    }//GEN-LAST:event_zamknij_zamknijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(okno_glowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(okno_glowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(okno_glowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(okno_glowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new okno_glowne().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK_logowanie;
    private javax.swing.JFrame haslo;
    private javax.swing.JButton haslo_1;
    private javax.swing.JButton haslo_2;
    private javax.swing.JButton haslo_3;
    private javax.swing.JButton haslo_4;
    private javax.swing.JButton haslo_5;
    private javax.swing.JButton haslo_6;
    private javax.swing.JButton haslo_7;
    private javax.swing.JButton haslo_8;
    private javax.swing.JButton haslo_9;
    private javax.swing.JButton haslo_kasuj;
    private javax.swing.JButton haslo_ok;
    private javax.swing.JTextField haslo_tekst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton klawiatura;
    private javax.swing.JFrame komunikat;
    private javax.swing.JTextArea komunikat_tekst;
    private javax.swing.JButton komunikat_zamknij;
    private javax.swing.JLabel login;
    private javax.swing.JTextField login_logowanie;
    private javax.swing.JFrame logowanie;
    private javax.swing.JButton strzalki;
    private javax.swing.JFrame strzalki_okno;
    private javax.swing.JLabel tlo;
    private javax.swing.JButton uprawnienia;
    private javax.swing.JButton uzytkownik;
    private javax.swing.JButton wirusy;
    private javax.swing.JButton wirusy_nastepny;
    private javax.swing.JFrame wirusy_okno;
    private javax.swing.JTextArea wirusy_opis;
    private javax.swing.JButton wirusy_poprzedni;
    private javax.swing.JButton wirusy_zamknij;
    private javax.swing.JLabel wirusy_zdjecie;
    private javax.swing.JButton zaloguj;
    private javax.swing.JButton zamknij;
    private javax.swing.JButton zamknij_1;
    private javax.swing.JButton zamknij_2;
    private javax.swing.JButton zamknij_3;
    private javax.swing.JButton zamknij_4;
    private javax.swing.JButton zamknij_5;
    private javax.swing.JFrame zamknij_haslo;
    private javax.swing.JButton zamknij_zamknij;
    private javax.swing.JButton zgony;
    private javax.swing.JButton zgony_nastepny;
    private javax.swing.JFrame zgony_okno;
    private javax.swing.JTextArea zgony_opis;
    private javax.swing.JButton zgony_poprzedni;
    private javax.swing.JButton zgony_wyjdz;
    private javax.swing.JLabel zgony_zdjecie;
    // End of variables declaration//GEN-END:variables
}
